# Generated by Django 4.2.7 on 2026-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_payment_method_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_status_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_transaction_event_status_idx',
        ),
    ]
