# Generated by Django 6.0.6 on 2026-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_transaction_payments_transaction_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('paystack', 'Paystack')], default='mpesa', max_length=20),
        ),
    ]
