# Generated by Django 4.2.7 on 2026-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketcategory",
            options={"ordering": ["display_order", "price"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticketcategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="bundle_label",
            field=models.CharField(
                blank=True, help_text="e.g. 'Admits 2', 'Table of 8'", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="bundle_size",
            field=models.PositiveIntegerField(
                default=1, help_text="How many people this ticket admits"
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first"
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="is_bundle",
            field=models.BooleanField(
                default=False, help_text="Enable for Couple Pass, Squad, Table bookings"
            ),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="Free / RSVP — no payment required"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("vip", "VIP"),
                    ("early_bird", "Early Bird"),
                    ("student", "Student"),
                    ("couples", "Couples Pass"),
                    ("group", "Group / Squad"),
                    ("table", "Table Booking"),
                    ("free", "Free / RSVP"),
                    ("press", "Press / Media"),
                    ("backstage", "Backstage"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="sales_end",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank to sell until event date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="sales_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Leave blank to start selling immediately",
                null=True,
            ),
        ),
    ]
