# Generated by Django 4.2.7 on 2026-05-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_ticketcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code people type in (e.g. SOUL20)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed Amount (Ksh)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount or % value", max_digits=10
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 for unlimited"),
                ),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if valid for ALL events",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="events.event",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The DJ or Influencer this code belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoter_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
