# Generated by Django 4.2.7 on 2026-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
