# Generated by Django 4.2.7 on 2026-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_organizer_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_category_active_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandise',
            name='events_merchandise_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandise',
            name='events_merchandise_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandise',
            name='events_merchandise_seller_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandise',
            name='events_merchandise_category_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandise',
            name='events_merchandise_seller_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandiseorder',
            name='events_merchandiseorder_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandiseorder',
            name='events_merchandiseorder_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandiseorder',
            name='events_merchandiseorder_buyer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchandiseorder',
            name='events_merchandiseorder_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcategory',
            name='events_ticketcategory_is_free_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcategory',
            name='events_ticketcategory_available_tickets_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcategory',
            name='events_ticketcategory_event_available_idx',
        ),
    ]
