# Generated by Django 4.2.7 on 2026-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_merchandise', '0004_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellermerchandise',
            name='seller_merchandise_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandise',
            name='seller_merchandise_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandise',
            name='seller_merchandise_seller_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandise',
            name='seller_merchandise_category_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandiseorder',
            name='seller_merchandise_order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandiseorder',
            name='seller_merchandise_order_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandiseorder',
            name='seller_merchandise_order_buyer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellermerchandiseorder',
            name='seller_merchandise_order_seller_status_idx',
        ),
    ]
