# Generated by Django 4.2.7 on 2026-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Category description (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Recommended size: 1200x675px (16:9 ratio)",
                null=True,
                upload_to="blog_images/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Check to make this post visible on the website",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Search engine summary (Best for SEO, 120-160 chars)",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
