# Generated by Django 4.2.7 on 2026-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_is_published_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_published_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author_published_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_category_published_idx',
        ),
    ]
